### ISSUE TITLE
Debian packages for berry

### ISSUE THREAD

**Issue by barnumbirr** [JLErvin/berry-doc#2]
Hey,

I've created Debian packages for berry over at [barnumbirr/berry-debian](https://github.com/barnumbirr/berry-debian) and was wondering if you be interested in adding them to the documentation.

If you're up for it, just tell me what you want the formatting to look like and I'll create a PR.

Thanks a lot.
Cheers.

**Comment by JLErvin** [comment]
Yes I'd love to add this. Just replicate something similar to the other distro-specific instructions [here](https://github.com/JLErvin/berry-doc/blob/master/installation.md).
